// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniFilteringproject.Data;

#nullable disable

namespace UniFilteringproject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204080638_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniFilteringproject.Models.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("UniFilteringproject.Models.AppointedMalshab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CorpId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorpId");

                    b.ToTable("AppointedMalshab");
                });

            modelBuilder.Entity("UniFilteringproject.Models.CorAbi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbiLevel")
                        .HasColumnType("int");

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.Property<int>("CorpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("CorpId");

                    b.ToTable("CorAbi");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Corp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DoesBlock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFull")
                        .HasColumnType("bit");

                    b.Property<int>("MinMalshabs")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Corps");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Haiils", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UniId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniId");

                    b.ToTable("Haiils");
                });

            modelBuilder.Entity("UniFilteringproject.Models.MalAbi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbiLevel")
                        .HasColumnType("int");

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.Property<int>("MalshabId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("MalshabId");

                    b.ToTable("MalAbi");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Malshab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dapar")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Profile")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Malshabs");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Uni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Uni");
                });

            modelBuilder.Entity("UniFilteringproject.Models.AppointedMalshab", b =>
                {
                    b.HasOne("UniFilteringproject.Models.Corp", null)
                        .WithMany("Malshabim")
                        .HasForeignKey("CorpId");
                });

            modelBuilder.Entity("UniFilteringproject.Models.CorAbi", b =>
                {
                    b.HasOne("UniFilteringproject.Models.Ability", "ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniFilteringproject.Models.Corp", "corp")
                        .WithMany()
                        .HasForeignKey("CorpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ability");

                    b.Navigation("corp");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Haiils", b =>
                {
                    b.HasOne("UniFilteringproject.Models.Uni", null)
                        .WithMany("ListOfHaiils")
                        .HasForeignKey("UniId");
                });

            modelBuilder.Entity("UniFilteringproject.Models.MalAbi", b =>
                {
                    b.HasOne("UniFilteringproject.Models.Ability", "ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniFilteringproject.Models.Malshab", "malshab")
                        .WithMany()
                        .HasForeignKey("MalshabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ability");

                    b.Navigation("malshab");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Corp", b =>
                {
                    b.Navigation("Malshabim");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Uni", b =>
                {
                    b.Navigation("ListOfHaiils");
                });
#pragma warning restore 612, 618
        }
    }
}
