// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniFilteringproject.Data;

#nullable disable

namespace UniFilteringproject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124113914_13")]
    partial class _13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniFilteringproject.Models.AppointedMalshab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CorpId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorpId");

                    b.ToTable("AppointedMalshab");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Corp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DoesBlock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFull")
                        .HasColumnType("bit");

                    b.Property<int>("MinMalshabs")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TheCorps");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Haiils", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UniId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniId");

                    b.ToTable("Haiils");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Malshab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dapar")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Profile")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TheMalshabs");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Uni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TheUni");
                });

            modelBuilder.Entity("UniFilteringproject.Models.AppointedMalshab", b =>
                {
                    b.HasOne("UniFilteringproject.Models.Corp", null)
                        .WithMany("Malshabim")
                        .HasForeignKey("CorpId");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Haiils", b =>
                {
                    b.HasOne("UniFilteringproject.Models.Uni", null)
                        .WithMany("ListOfHaiils")
                        .HasForeignKey("UniId");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Corp", b =>
                {
                    b.Navigation("Malshabim");
                });

            modelBuilder.Entity("UniFilteringproject.Models.Uni", b =>
                {
                    b.Navigation("ListOfHaiils");
                });
#pragma warning restore 612, 618
        }
    }
}
